### ISSUE TITLE
yarn for packages doesn't work

### ISSUE THREAD

**Issue by Padlina** [nie-ine/NIE-OS#58] opened 2018-10-24 07:26 UTC
Dear Jan,
I just made a fresh clone, and wanted to notice that the yarn command doesn't work:
`➜  nieOS git:(devel) yarn
yarn install v1.9.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @angular-devkit/build-angular@0.6.8: The engine "node" is incompatible with this module. Expected version ">= 8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`
It worked with npm install.
So, we should either fix this or edit the installation notes.

**Comment by janCstoffregen** [comment] 2018-10-24 07:37
does yarn work after deleting package-lock.json?

**Comment by Padlina** [comment] 2018-10-24 07:43
@janCstoffregen After deleting the package-lock.json I don't have the warning anymore, but still this error with the engine node:
`➜  nieOS git:(devel) ✗ yarn
yarn install v1.9.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error @angular-devkit/build-angular@0.6.8: The engine "node" is incompatible with this module. Expected version ">= 8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by janCstoffregen** [comment] 2018-10-31 08:31
can we close this? @Padlina

**Comment by musicEnfanthen** [comment] 2019-02-21 12:36
With a new fresh fork `yarn install` is not working, also not after deleting the lock files. Neither is `npm install`.  Using node 10.15.1, yarn 1.13.0.

**Comment by janCstoffregen** [comment] 2019-02-22 15:05
is it the same error as mentioned when this issue was opened?

**Comment by janCstoffregen** [comment] 2019-02-22 15:29
it's working on macOS, which Ubuntu - Version are you using? Or which OS?

**Comment by janCstoffregen** [comment] 2019-02-25 13:33
I have updated the package.json: https://github.com/nie-ine/NIE-OS/pull/177/commits/d5c5d8cd3e7d0c9fb7eff4efa3325dd3d371c281

it works on macOS, would you mind trying it one more time @Padlina @musicEnfanthen @domsteinbach 

Thanks and best regards,
Jan

**Comment by janCstoffregen** [comment] 2019-02-25 13:35
in branch 2019-02

and start with ng s --poll 1000, a workaround for the current bug in devkit/angular

**Comment by musicEnfanthen** [comment] 2019-02-25 16:22
> it's working on macOS, which Ubuntu - Version are you using? Or which OS?

It was neither working on macOs nor Windows 10 (branch `devel`). Got the following error:

> yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "[…]/NIE-OS/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by musicEnfanthen** [comment] 2019-02-25 16:27
Ok, workaround works on macOs, but a lot of "incorrect peer dependency" warnings

>yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @knora/core@6.5.0" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @knora/core@6.5.0" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "@angular/common@^6.1.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "@angular/core@^6.1.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "@angular/forms@^6.1.0".
warning " > ngx-editor@4.1.0" has unmet peer dependency "font-awesome@^4.7.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "rxjs@~6.2.0".
warning "nie-ine > @angular/cdk@5.2.5" has incorrect peer dependency "@angular/core@>=5.0.0 <7.0.0".
warning "nie-ine > @angular/cdk@5.2.5" has incorrect peer dependency "@angular/common@>=5.0.0 <7.0.0".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "rxjs@^5.5.0".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/core@5.2.11".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/common@5.2.11".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/platform-browser@5.2.11".
[4/4] 🔨  Building fresh packages...
✨  Done in 28.39s.

Will also check on Win10

**Comment by musicEnfanthen** [comment] 2019-02-25 16:29
> and start with ng s --poll 1000, a workaround for a current bug in devkit/angular

Simple `ng s` works on macOS, indeed

**Comment by musicEnfanthen** [comment] 2019-02-25 20:26
Ok, on WIn10 and devel branch it fails:

> yarn install v1.13.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning uglifyjs@2.4.11: uglifyjs is deprecated - use uglify-js instead.
warning @angular-devkit/build-angular > istanbul@0.4.5: This module is no longer maintained, try this instead:
  npm i nyc
Visit https://istanbul.js.org/integrations for other alternatives.
warning karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
warning karma > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning karma > log4js > nodemailer > mailcomposer@4.0.1: This project is unmaintained
warning karma > log4js > nodemailer > socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
warning karma > log4js > nodemailer > mailcomposer > buildmail@4.0.1: This project is unmaintained
warning karma > socket.io > engine.io > uws@9.14.0: New code is available at github.com/uNetworking/uWebSockets.js
warning karma > log4js > loggly > request > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning karma > log4js > loggly > request > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning karma > log4js > loggly > request > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning karma > log4js > loggly > request > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning karma > log4js > loggly > request > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning karma > log4js > loggly > request > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @angular/forms@6.1.10" has incorrect peer dependency "@angular/core@6.1.10".
warning " > @angular/forms@6.1.10" has incorrect peer dependency "@angular/common@6.1.10".
warning " > @angular/forms@6.1.10" has incorrect peer dependency "@angular/platform-browser@6.1.10".
warning " > ng2-ace-editor@0.3.9" has incorrect peer dependency "@angular/core@^7.0.0".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "rxjs@^5.5.0".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/core@5.2.11".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/common@5.2.11".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/platform-browser@5.2.11".
warning " > karma-jasmine-html-reporter@1.4.0" has incorrect peer dependency "jasmine-core@>=3.3".
[4/4] Building fresh packages...
[1/6] ⠈ rdf-canonize
[2/6] ⠈ bcrypt
[-/6] ⠈ waiting...
[4/6] ⠈ node-sass
error C:\[...]\fork_NIE-OS\node_modules\rdf-canonize: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\[...]\fork_NIE-OS\node_modules\rdf-canonize
Output:
C:\[...]\fork_NIE-OS\node_modules\rdf-canonize>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\www\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\[...]\fork_NIE-OS\node_modules\rdf-canonize

**Comment by musicEnfanthen** [comment] 2019-02-25 20:33
Workaround on `2019-02` branch runs fine on Win, too, but with a lot of warnings, too:

> yarn install v1.13.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning uglifyjs@2.4.11: uglifyjs is deprecated - use uglify-js instead.
warning karma > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @knora/core@6.6.0" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @knora/core@6.6.0" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "@angular/common@^6.1.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "@angular/core@^6.1.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "@angular/forms@^6.1.0".
warning " > ngx-editor@4.1.0" has unmet peer dependency "font-awesome@^4.7.0".
warning " > ngx-editor@4.1.0" has incorrect peer dependency "rxjs@~6.2.0".
warning "nie-ine > @angular/cdk@5.2.5" has incorrect peer dependency "@angular/core@>=5.0.0 <7.0.0".
warning "nie-ine > @angular/cdk@5.2.5" has incorrect peer dependency "@angular/common@>=5.0.0 <7.0.0".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "rxjs@^5.5.0".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/core@5.2.11".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/common@5.2.11".
warning "nie-ine > @angular/forms@5.2.11" has incorrect peer dependency "@angular/platform-browser@5.2.11".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 165.43s.

**Comment by musicEnfanthen** [comment] 2019-02-25 20:36
And also on Win starting with `ng s` without problems

**Comment by janCstoffregen** [comment] 2019-02-26 10:23
ok, are you able to compile and start it now? The warnings can be ignored for now...

**Comment by janCstoffregen** [comment] 2019-02-26 10:24
and please let me know if you would like to start it with MongoDB, then we need to do a video call really quick.

**Comment by musicEnfanthen** [comment] 2019-02-26 10:44
yes, it compiles and starts on all systems now

**Comment by janCstoffregen** [comment] 2019-02-26 10:51
ok, cool, so I will close this issue for now, thank you for this information! Would you like to start NIE-OS together on your machine? Then we should do a video call soon!

**Closed by janCstoffregen** 2019-02-26 10:51 UTC
